# Generated by Django 4.0.1 on 2022-01-05 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_product_main_picture_product_price_alter_product_id')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('main_picture', models.ImageField(blank=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
        ),
    ]
